//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materialise.FrontendDays.Bot.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Materialise.FrontendDays.Bot.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоя категория - {0}
        ///	
        ///	{1}.
        /// </summary>
        internal static string AllCorrectResponse {
            get {
                return ResourceManager.GetString("AllCorrectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты уже играл, чертила.
        /// </summary>
        internal static string AlreadyPlayed {
            get {
                return ResourceManager.GetString("AlreadyPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	{0} программистов - {1}.
        /// </summary>
        internal static string CategoryInfoFormat {
            get {
                return ResourceManager.GetString("CategoryInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поехали!.
        /// </summary>
        internal static string GameStarted {
            get {
                return ResourceManager.GetString("GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет {0} {1}! Добро пожаловать в игру.
        /// </summary>
        internal static string HelloFormat {
            get {
                return ResourceManager.GetString("HelloFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тебе не повезло :(.
        /// </summary>
        internal static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для начала сыграй.
        /// </summary>
        internal static string StatsDenied {
            get {
                return ResourceManager.GetString("StatsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данный момент вокруг тебя такие люди:
        ///	.
        /// </summary>
        internal static string StatsHeaderFormat {
            get {
                return ResourceManager.GetString("StatsHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты выиграл! Подходи на сцену за призом.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
    }
}
